services:
  db:
    image: postgres:16
    container_name: sis_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sis_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} "]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: system_programming_project-app:latest
    container_name: sis_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: student_information
      DB_USER: zuleyha
      DB_PASSWORD: zuleyha1
    ports:
      - "8080:8080"
    networks:
      - sis_network

volumes:
  postgres_data:

networks:
  sis_network:
    driver: bridge
   
